import * as SecureStore from "expo-secure-store";
import { authenticate, clearToken, currentAccount, deleteAccount, listHistory, removeHistory, saveHistory, signOut, token } from "./authService";

jest.mock("expo-secure-store", () => ({ getItemAsync: jest.fn(), setItemAsync: jest.fn(), deleteItemAsync: jest.fn() }));
jest.mock("../config/api", () => ({ apiBaseUrl: "http://example.test" }));

const fetchMock = jest.fn();
const summary = { outcome: "supported" as const, confirmed_nominal_size: "1/2" as const, repair_method_id: "two_slip_coupling_section_replacement" as const, measured_gap_range_status: "within_mvp_range", generic_parts_item_names: ["PVC pipe"], safety_and_limitation_text: ["Verify labels"] };
const ok = (body: unknown = {}): Response => ({ ok: true, status: 200, json: async () => body } as Response);
beforeEach(() => { Object.defineProperty(global, "fetch", { configurable: true, value: fetchMock }); jest.clearAllMocks(); (SecureStore.getItemAsync as jest.Mock).mockResolvedValue(null); });

test("saves, loads, and clears a token with SecureStore only", async () => { fetchMock.mockResolvedValue(ok({ access_token: "token" })); await authenticate("/api/v1/auth/register", "a@example.com", "long-enough-password"); expect(SecureStore.setItemAsync).toHaveBeenCalledWith("pipepatch_access_token", "token"); (SecureStore.getItemAsync as jest.Mock).mockResolvedValue("token"); await expect(token()).resolves.toBe("token"); await clearToken(); expect(SecureStore.deleteItemAsync).toHaveBeenCalledWith("pipepatch_access_token"); });
test("register and login map credentials and generic failure stores no token", async () => { fetchMock.mockResolvedValue(ok({ access_token: "token" })); await authenticate("/api/v1/auth/register", "a@example.com", "long-enough-password"); await authenticate("/api/v1/auth/login", "a@example.com", "long-enough-password"); expect(fetchMock.mock.calls.map((call) => call[0])).toEqual(["http://example.test/api/v1/auth/register", "http://example.test/api/v1/auth/login"]); fetchMock.mockResolvedValue({ ok: false, status: 401 }); await expect(authenticate("/api/v1/auth/login", "a@example.com", "wrong-password")).rejects.toThrow("Authentication unavailable"); });
test("401, sign out, and account deletion clear local token", async () => { (SecureStore.getItemAsync as jest.Mock).mockResolvedValue("token"); fetchMock.mockResolvedValue({ ok: false, status: 401 }); await expect(currentAccount()).rejects.toThrow(); fetchMock.mockResolvedValue(ok()); await signOut(); await deleteAccount(); expect(SecureStore.deleteItemAsync).toHaveBeenCalledTimes(3); });
test("history save sends only the approved text summary", async () => { fetchMock.mockResolvedValue(ok({ id: "one", title: "Repair", created_at: "now", summary })); await saveHistory("Repair", summary); const body = JSON.parse((fetchMock.mock.calls[0][1] as RequestInit).body as string); expect(Object.keys(body.summary).sort()).toEqual(["confirmed_nominal_size", "generic_parts_item_names", "measured_gap_range_status", "outcome", "repair_method_id", "safety_and_limitation_text"]); expect(JSON.stringify(body)).not.toMatch(/uri|quote|supplier|price|location/i); });
test("history list, deletion, empty and error paths are observable", async () => { fetchMock.mockResolvedValueOnce(ok([])).mockResolvedValueOnce(ok([{ id: "one", title: "Repair", created_at: "now", summary }])).mockResolvedValueOnce(ok()); await expect(listHistory()).resolves.toEqual([]); await expect(listHistory()).resolves.toMatchObject([{ id: "one", summary }]); await expect(removeHistory("one")).resolves.toBeUndefined(); fetchMock.mockResolvedValue({ ok: false, status: 500 }); await expect(listHistory()).rejects.toThrow("History unavailable"); });
