import { authHistoryReducer, initialAuthHistoryState, mayDeleteAccount, maySaveSummary } from "./authHistoryPolicy";

test("rejects a second auth submit while the first request is in flight", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 1 }); expect(authHistoryReducer(loading, { type: "START", operationId: 2 })).toBe(loading); });
test("cancellation invalidates a pending auth result", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 1 }); const cancelled = authHistoryReducer(loading, { type: "CANCEL", operationId: 1 }); expect(authHistoryReducer(cancelled, { type: "SUCCESS", operationId: 1 })).toBe(cancelled); });
test("a stale auth failure cannot override a newer auth state", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 1 }); const newer = authHistoryReducer(loading, { type: "LOGOUT", operationId: 1 }); expect(authHistoryReducer(newer, { type: "FAILURE", operationId: 1 })).toBe(newer); });
test("rejects duplicate history save or delete while busy", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 4 }); expect(authHistoryReducer(loading, { type: "START", operationId: 5 })).toBe(loading); });
test("stale history success is ignored after account deletion", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 7 }); const deleted = authHistoryReducer(loading, { type: "LOGOUT", operationId: 7 }); expect(authHistoryReducer(deleted, { type: "SUCCESS", operationId: 7 })).toBe(deleted); });
test("retry starts a new history operation only after an error", () => { const loading = authHistoryReducer(initialAuthHistoryState, { type: "START", operationId: 1 }); const error = authHistoryReducer(loading, { type: "FAILURE", operationId: 1 }); expect(authHistoryReducer(error, { type: "RETRY", operationId: 2 })).toEqual({ status: "loading", operationId: 2, consent: false }); });
test("save summary requires explicit consent and a signed-in account", () => { expect(maySaveSummary(false, true)).toBe(false); expect(maySaveSummary(true, false)).toBe(false); expect(maySaveSummary(true, true)).toBe(true); });
test("anonymous navigation remains allowed because it does not require a token", () => { expect(maySaveSummary(false, false)).toBe(false); expect(initialAuthHistoryState.status).toBe("idle"); });
test("delete account requires destructive confirmation", () => { expect(mayDeleteAccount(false)).toBe(false); expect(mayDeleteAccount(true)).toBe(true); });
