import { initialPhotoFlow, photoFlowReducer } from "./photoFlow";
const image = { localUri: "file:///pipe.jpg", width: 1200, height: 1200, mimeType: "image/jpeg", fileSize: null, source: "camera" as const, originalOwnership: "app_owned" as const, normalizedStatus: "original" as const, appOwnedUris: ["file:///pipe.jpg"] };
const analysis = { is_mock: true as const, supported_case: false, material: null, pipe_schedule: null, nominal_size: null, damage_type: null, confidence: 0, summary: "Demo", evidence: [], unknowns: [], safety_flags: [], next_action: "Stop" };
test("only accepts a current prepared image and confirms from review", () => { const source = photoFlowReducer(photoFlowReducer(initialPhotoFlow, { type: "START" }), { type: "SHOW_SOURCE" }); const preparing = photoFlowReducer(source, { type: "BEGIN_PREPARE", operationId: 2 }); expect(photoFlowReducer(preparing, { type: "IMAGE_READY", operationId: 1, image })).toBe(preparing); const review = photoFlowReducer(preparing, { type: "IMAGE_READY", operationId: 2, image }); expect(photoFlowReducer(review, { type: "CONFIRM" }).ready?.status).toBe("ready_for_analysis"); });
test("rejects invalid transitions and cancellation invalidates", () => { expect(photoFlowReducer(initialPhotoFlow, { type: "CONFIRM" })).toBe(initialPhotoFlow); expect(photoFlowReducer({ ...initialPhotoFlow, screen: "camera" }, { type: "CANCEL", operationId: 5 }).screen).toBe("source"); });
test("replace and reset invalidate prior work", () => { const review = { ...initialPhotoFlow, screen: "review" as const, image, operationId: 2 }; const replaced = photoFlowReducer(review, { type: "REPLACE", operationId: 3 }); expect(replaced).toMatchObject({ screen: "source", image: null, operationId: 3 }); expect(photoFlowReducer({ ...review, screen: "ready" }, { type: "RESET", operationId: 4 })).toMatchObject({ screen: "home", operationId: 4 }); });
test("duplicate forward events are ignored", () => { const guidance = photoFlowReducer(initialPhotoFlow, { type: "START" }); expect(photoFlowReducer(guidance, { type: "START" })).toBe(guidance); const source = photoFlowReducer(guidance, { type: "SHOW_SOURCE" }); const preparing = photoFlowReducer(source, { type: "BEGIN_PREPARE", operationId: 1 }); expect(photoFlowReducer(preparing, { type: "BEGIN_PREPARE", operationId: 2 })).toBe(preparing); });
test("uploads only after confirmation and ignores stale or duplicate results", () => { const review = { ...initialPhotoFlow, screen: "review" as const, image }; const ready = photoFlowReducer(review, { type: "CONFIRM" }); const uploading = photoFlowReducer(ready, { type: "BEGIN_ANALYSIS", operationId: 4 }); expect(photoFlowReducer(uploading, { type: "ANALYSIS_SUCCESS", operationId: 3, analysis })).toBe(uploading); expect(photoFlowReducer(uploading, { type: "BEGIN_ANALYSIS", operationId: 5 })).toBe(uploading); expect(photoFlowReducer(uploading, { type: "ANALYSIS_SUCCESS", operationId: 4, analysis })).toMatchObject({ screen: "result", analysis }); });
test("cancels or retries an analysis only from its permitted state", () => { const uploading = { ...initialPhotoFlow, screen: "uploading" as const, image, operationId: 2 }; expect(photoFlowReducer(uploading, { type: "CANCEL_ANALYSIS", operationId: 2 })).toMatchObject({ screen: "review", image }); const failed = photoFlowReducer(uploading, { type: "ANALYSIS_FAILURE", operationId: 2 }); expect(photoFlowReducer(failed, { type: "RETRY_ANALYSIS", operationId: 3 })).toMatchObject({ screen: "uploading", operationId: 3 }); expect(photoFlowReducer(initialPhotoFlow, { type: "RETRY_ANALYSIS", operationId: 3 })).toBe(initialPhotoFlow); });
