import { blockedCategoryMessage, categoryFor, DAMAGE_LABELS, historyTaxonomyOnly, mayContinueToSafety } from "./taxonomyPolicy";
import type { AnalysisResponse } from "../types/analysis";
const analysis = (changes: Partial<AnalysisResponse> = {}): AnalysisResponse => ({ is_mock: false, supported_case: true, material: null, pipe_schedule: null, nominal_size: null, damage_type: null, damage_category: "clean_transverse_cut", confidence: .8, summary: "", evidence: [], unknowns: [], safety_flags: [], next_action: "", ...changes });

test.each(Object.entries(DAMAGE_LABELS))("maps %s to a human-readable label", (category, label) => { expect(label).toMatch(/[A-Z]/); expect(categoryFor(analysis({ damage_category: category as AnalysisResponse["damage_category"] }))).toBe(category); });
test("permits clean transverse cut navigation only for a supported live analysis", () => { expect(mayContinueToSafety(analysis())).toBe(true); expect(mayContinueToSafety(analysis({ supported_case: false }))).toBe(false); });
test.each(["crack_or_split", "puncture_or_hole", "active_leak_or_wet_soil", "separated_or_broken_fitting", "valve_or_manifold_damage", "sprinkler_head_damage", "no_visible_damage", "unknown_or_unsupported"] as const)("blocks %s with a safe next action", (category) => { expect(mayContinueToSafety(analysis({ damage_category: category }))).toBe(false); expect(blockedCategoryMessage(category)).toMatch(/DIY repair guidance|Retake/); });
test("mock analysis remains blocked regardless of category", () => { expect(mayContinueToSafety(analysis({ is_mock: true }))).toBe(false); expect(mayContinueToSafety(analysis({ is_mock: true, damage_category: "crack_or_split" }))).toBe(false); });
test("history taxonomy sanitizer returns only the stable taxonomy ID", () => { const saved = historyTaxonomyOnly(analysis({ damage_category: "puncture_or_hole", summary: "raw AI text" })); expect(saved).toEqual({ damage_category: "puncture_or_hole" }); expect(JSON.stringify(saved)).not.toMatch(/uri|coordinate|summary|quote|supplier|location/i); });
