import { useEffect, useRef, useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { AppButton } from "../components/AppButton";
import { authenticate, currentAccount, deleteAccount, listHistory, removeHistory, signOut } from "../services/authService";
import { colors } from "../theme";
import type { Account, HistoryEntry } from "../types/auth";

export function AccountScreen({ onBack }: { onBack: () => void }): React.JSX.Element {
  const [account, setAccount] = useState<Account | null>(null); const [history, setHistory] = useState<HistoryEntry[]>([]); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [confirmDelete, setConfirmDelete] = useState(false); const op = useRef(0);
  const load = (): void => { const id = ++op.current; setBusy(true); void currentAccount().then((value) => Promise.all([value, listHistory()])).then(([value, entries]) => { if (op.current === id) { setAccount(value); setHistory(entries); } }).catch(() => { if (op.current === id) setAccount(null); }).finally(() => { if (op.current === id) setBusy(false); }); };
  useEffect(load, []);
  const submit = (path: "/api/v1/auth/login" | "/api/v1/auth/register"): void => { if (busy) return; const id = ++op.current; setBusy(true); setError(null); void authenticate(path, email, password).then(() => { setPassword(""); if (op.current === id) load(); }).catch(() => { if (op.current === id) setError("Unable to continue. Check your details and try again."); }).finally(() => { if (op.current === id) setBusy(false); }); };
  if (!account) return <KeyboardAvoidingView behavior={Platform.select({ ios: "padding", default: undefined })} style={s.fill}><Text style={s.title}>Optional account</Text><Text style={s.body}>Continue without an account at any time. Passwords are sent only to this backend and are never stored in the app.</Text><TextInput accessibilityLabel="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={s.input} placeholder="Email" /><TextInput accessibilityLabel="Password" secureTextEntry value={password} onChangeText={setPassword} style={s.input} placeholder="Password (12+ characters)" />{error && <Text style={s.error}>{error}</Text>}<AppButton label="Sign in" disabled={busy} onPress={() => submit("/api/v1/auth/login")} /><AppButton label="Create account" variant="secondary" disabled={busy} onPress={() => submit("/api/v1/auth/register")} /><AppButton label="Continue without account" variant="secondary" onPress={onBack} /></KeyboardAvoidingView>;
  return <><Text style={s.title}>Account</Text><Text style={s.body}>{account.email}</Text><Text style={s.heading}>Saved repair summaries</Text>{history.length === 0 ? <Text style={s.body}>No saved summaries.</Text> : history.map((item) => <View style={s.card} key={item.id}><Text style={s.body}>{item.title}</Text><Text style={s.caption}>{item.summary.outcome} · {item.summary.confirmed_nominal_size ?? "size not confirmed"}</Text><AppButton label="Delete summary" variant="secondary" onPress={() => { void removeHistory(item.id).then(load); }} /></View>)}<AppButton label="Refresh history" variant="secondary" onPress={load} /><AppButton label="Sign out" variant="secondary" onPress={() => { void signOut().then(load); }} />{confirmDelete ? <><Text style={s.error}>This permanently deletes your account and all saved summaries.</Text><AppButton label="Permanently delete account" onPress={() => { void deleteAccount().then(load); }} /></> : <AppButton label="Delete account" variant="secondary" onPress={() => setConfirmDelete(true)} />}<AppButton label="Back" variant="secondary" onPress={onBack} /></>;
}
const s = StyleSheet.create({ fill: { gap: 12 }, title: { color: colors.green, fontSize: 30, fontWeight: "800" }, heading: { color: colors.green, fontSize: 20, fontWeight: "800" }, body: { color: colors.ink, fontSize: 16, lineHeight: 23 }, caption: { color: colors.muted, fontSize: 13 }, input: { borderColor: colors.green, borderWidth: 1, borderRadius: 8, padding: 12 }, error: { color: colors.danger, fontWeight: "700" }, card: { backgroundColor: colors.white, borderRadius: 12, gap: 8, padding: 12 } });
