import { useRef, useState } from "react";
import { Image, Pressable, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { AppButton } from "../components/AppButton";
import { requestMeasurements } from "../services/measurementService";
import { colors } from "../theme";
import type { SelectedImage } from "../types/image";
import type { ImagePoint, MeasurementResponse } from "../types/measurement";
import { containLayout, displayToImagePoint } from "../utils/responsive";

export function AssistedMeasurementScreen({ image, onBack, onRetake, onSuggestion }: { image: SelectedImage; onBack: () => void; onRetake: () => void; onSuggestion: (size: "1/2" | "3/4" | "1" | null) => void }): React.JSX.Element {
  const viewport = useWindowDimensions(); const [box, setBox] = useState({ width: Math.max(1, viewport.width - 48), height: 300 }); const [points, setPoints] = useState<ImagePoint[]>([]); const [busy, setBusy] = useState(false); const [result, setResult] = useState<MeasurementResponse | null>(null); const op = useRef(0); const layout = containLayout(box, { width: image.width, height: image.height });
  const tap = (x: number, y: number): void => { if (busy || points.length === 4) return; const point = displayToImagePoint({ x, y }, layout, { width: image.width, height: image.height }); if (point) setPoints([...points, point]); };
  const submit = (): void => { if (points.length !== 4 || busy) return; const id = ++op.current; setBusy(true); const controller = new AbortController(); void requestMeasurements(image, { diameterStart: points[0], diameterEnd: points[1], gapStart: points[2], gapEnd: points[3] }, controller.signal).then((value) => { if (id === op.current) { setResult(value); onSuggestion(value.suggested_nominal_size); } }).catch(() => { if (id === op.current) setResult(null); }).finally(() => { if (id === op.current) setBusy(false); }); };
  const prompt = ["Tap one visible outer pipe edge.", "Tap the opposite outer pipe edge.", "Tap one clean cut end.", "Tap the opposite cut end."][points.length] ?? "All points selected.";
  if (result) return <><Text style={styles.eyebrow}>ASSISTED MEASUREMENT</Text><Text style={styles.title}>{result.status === "measured" ? "Estimated measurements" : "Measurement needs a retake"}</Text>{result.status === "measured" && <View style={styles.card}><Text style={styles.value}>Estimated visible outside diameter: {result.estimated_outer_diameter_mm} mm</Text><Text style={styles.value}>Estimated cut gap: {result.estimated_gap_mm} mm</Text><Text style={styles.body}>Closest supported size suggestion: {result.suggested_nominal_size ?? "None"}</Text><Text style={styles.body}>Quality: {Math.round(result.quality_score * 100)}%</Text></View>}<View style={styles.card}>{result.limitations.map((x) => <Text key={x} style={styles.body}>• {x}</Text>)}{result.retake_reasons.map((x) => <Text key={x} style={styles.body}>• {x}</Text>)}</View><AppButton label="Retake" onPress={onRetake} /><AppButton label="Back to calibration" variant="secondary" onPress={onBack} /></>;
  return <><Text style={styles.eyebrow}>ASSISTED MEASUREMENT</Text><Text style={styles.title}>Draw two visible lines</Text><Text style={styles.body}>Hold the camera above. Tap pipe edges—not shadows—and cut ends—not the marker. Use only for a clean straight cut; retake if angled, hidden, blurred, or covered by soil.</Text><Text style={styles.prompt}>{prompt}</Text><Pressable accessibilityLabel="Calibration image measurement surface" onLayout={(event) => setBox(event.nativeEvent.layout)} onPress={(event) => tap(event.nativeEvent.locationX, event.nativeEvent.locationY)} style={styles.imageBox}><Image source={{ uri: image.localUri }} resizeMode="contain" style={StyleSheet.absoluteFill} />{points.map((point, index) => <View key={`${point.x}-${point.y}`} style={[styles.point, { left: layout.left + point.x * layout.width / image.width - 6, top: layout.top + point.y * layout.height / image.height - 6 }]}><Text>{index + 1}</Text></View>)}</Pressable><Text style={styles.body}>Diameter: points 1–2. Gap: points 3–4.</Text><AppButton label="Reset diameter line" variant="secondary" disabled={busy || points.length < 1} onPress={() => setPoints(points.slice(2))} /><AppButton label="Reset gap line" variant="secondary" disabled={busy || points.length < 3} onPress={() => setPoints(points.slice(0, 2))} /><AppButton label={busy ? "Measuring…" : "Submit assisted measurement"} disabled={points.length !== 4 || busy} onPress={submit} /><AppButton label="Cancel" variant="secondary" onPress={() => { op.current += 1; onBack(); }} /></>;
}
const styles = StyleSheet.create({ eyebrow: { color: colors.limeDark, fontSize: 13, fontWeight: "800" }, title: { color: colors.green, fontSize: 28, fontWeight: "800" }, body: { color: colors.ink, fontSize: 15, lineHeight: 22 }, prompt: { color: colors.green, fontSize: 17, fontWeight: "800" }, imageBox: { backgroundColor: colors.creamDark, height: 300, position: "relative", width: "100%" }, point: { alignItems: "center", backgroundColor: colors.lime, borderRadius: 12, height: 24, justifyContent: "center", position: "absolute", width: 24 }, card: { backgroundColor: colors.white, borderColor: colors.creamDark, borderRadius: 16, borderWidth: 1, gap: 8, padding: 16 }, value: { color: colors.green, fontSize: 17, fontWeight: "800" } });
