import { useRef, useState } from "react";
import { Linking, StyleSheet, Text, TextInput, View } from "react-native";
import { AppButton } from "../components/AppButton";
import { requestSuppliers } from "../services/supplierService";
import { colors } from "../theme";
import type { SupplierSearchRequest, SupplierSearchResponse } from "../types/supplier";
import { makeSupplierRequest, validSupplierArea } from "../utils/supplierPolicy";

export function SupplierSearchScreen({ baseRequest, onBack }: { baseRequest: Omit<SupplierSearchRequest, "area" | "radius_km" | "max_results">; onBack: () => void }): React.JSX.Element {
  const [area, setArea] = useState(""); const [radius, setRadius] = useState("5"); const [result, setResult] = useState<SupplierSearchResponse | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const op = useRef(0); const controller = useRef<AbortController | null>(null);
  const search = (): void => { const numericRadius = Number(radius); if (busy || !validSupplierArea(area) || !Number.isFinite(numericRadius) || numericRadius < 0.1 || numericRadius > 10) { if (!busy) setError("Enter a general city, area, or postcode and a radius from 0.1 to 10 km."); return; } const id = ++op.current; const abort = new AbortController(); controller.current = abort; setBusy(true); setError(null); void requestSuppliers(makeSupplierRequest(baseRequest, area, numericRadius), abort.signal).then((value) => { if (op.current === id) setResult(value); }).catch((reason: unknown) => { if (op.current === id && !(reason instanceof DOMException && reason.name === "AbortError")) setError("Nearby discovery is unavailable. Try again or use the category search link."); }).finally(() => { if (op.current === id) setBusy(false); }); };
  const cancel = (): void => { ++op.current; controller.current?.abort(); setBusy(false); onBack(); };
  return <><Text style={s.title}>Nearby materials</Text><Text style={s.body}>Enter only a general city, area, or postcode. This search is sent once when you tap Search; it is not saved by PipePatch.</Text><TextInput accessibilityLabel="General city, area, or postcode" value={area} onChangeText={setArea} placeholder="City, area, or postcode" style={s.input} /><TextInput accessibilityLabel="Search radius in kilometres" value={radius} onChangeText={setRadius} keyboardType="decimal-pad" placeholder="Radius (km)" style={s.input} /><AppButton label={busy ? "Searching…" : "Search nearby materials"} disabled={busy} onPress={search} />{busy && <Text style={s.body}>Searching public map data…</Text>}{error && <View style={s.error}><Text style={s.body}>{error}</Text><AppButton label="Retry search" onPress={search} /></View>}{result && <><Text style={s.caption}>{result.attribution} · {result.data_disclaimer}</Text>{result.reasons.map((reason) => <Text key={reason} style={s.errorText}>{reason}</Text>)}{result.suppliers.map((item) => <View key={item.directions_url} style={s.card}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.body}>{item.category} · {item.distance_km.toFixed(1)} km away</Text>{item.public_address && <Text style={s.body}>{item.public_address}</Text>}<Text style={s.caption}>{item.availability_message}</Text><AppButton label="Open directions" variant="secondary" onPress={() => { void Linking.openURL(item.directions_url); }} /></View>)}{result.fallback_message && <View style={s.card}><Text style={s.body}>{result.fallback_message}</Text><AppButton label="Search hardware stores on Maps" variant="secondary" onPress={() => { void Linking.openURL(result.fallback_search_url); }} /></View>}</>}<AppButton label={busy ? "Cancel search" : "Back to parts estimate"} variant="secondary" onPress={cancel} /></>;
}
const s = StyleSheet.create({ title: { color: colors.green, fontSize: 30, fontWeight: "800" }, body: { color: colors.ink, fontSize: 16, lineHeight: 23 }, caption: { color: colors.muted, fontSize: 13, lineHeight: 19 }, input: { borderColor: colors.green, borderWidth: 1, borderRadius: 8, padding: 12 }, card: { backgroundColor: colors.white, borderColor: colors.creamDark, borderRadius: 12, borderWidth: 1, gap: 8, padding: 12 }, error: { backgroundColor: "#F9E5E0", borderRadius: 12, gap: 8, padding: 12 }, errorText: { color: colors.danger, fontWeight: "700" }, cardTitle: { color: colors.green, fontSize: 18, fontWeight: "800" } });
