import { ChangeEvent, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { analyze, type Analysis } from "./api";
import "./style.css";

type View = "home" | "guidance" | "review" | "analysis";
const categoryLabel = (value?: string): string => (value ?? "unknown_or_unsupported").replaceAll("_", " ");
const isBlocked = (value: Analysis): boolean => value.is_mock || !value.supported_case || value.damage_category !== "clean_transverse_cut";

function App(): React.JSX.Element {
  const [view, setView] = useState<View>("home"); const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState<Analysis | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const current = useRef(0); const controller = useRef<AbortController | null>(null);
  const clear = (): void => { current.current++; controller.current?.abort(); setFile(null); setResult(null); setBusy(false); setError(""); };
  const select = (event: ChangeEvent<HTMLInputElement>): void => { const next = event.target.files?.[0] ?? null; if (next) { clear(); setFile(next); setView("review"); } };
  const submit = (): void => { if (!file || busy) return; const id = ++current.current; const abort = new AbortController(); controller.current = abort; setBusy(true); setError(""); void analyze(file, abort.signal).then(value => { if (current.current === id) { setResult(value); setView("analysis"); } }).catch(reason => { if (current.current === id && !(reason instanceof DOMException && reason.name === "AbortError")) setError("Analysis could not be completed. Retry or choose another image."); }).finally(() => { if (current.current === id) setBusy(false); }); };
  const cancel = (): void => { controller.current?.abort(); current.current++; setBusy(false); setView("review"); };
  return <main><header><b>PipePatch AI</b><span>Browser demo</span></header>{error && <p className="blocked" role="alert">{error}</p>}{view === "home" && <section><p className="eyebrow">OBSERVATION-ONLY ANALYSIS</p><h1>Clear photo. Cautious result.</h1><p>PipePatch retains the selected image only in this active browser session and sends it only after you confirm.</p><button onClick={() => setView("guidance")}>Prepare a pipe photo</button><p className="coming">Calibration, measurement, repair assessment, parts, suppliers, and accounts are coming next in the web demo.</p></section>}{view === "guidance" && <section><p className="eyebrow">PHOTO GUIDANCE</p><h2>Frame the repair area</h2><ul><li>Both damaged pipe ends</li><li>Pipe markings when visible</li><li>Complete ArUco marker and surrounding context</li><li>Good lighting and an unobstructed image</li></ul><label className="upload">Take or choose photo<input type="file" accept="image/*" capture="environment" onChange={select}/></label><button className="secondary" onClick={() => { clear(); setView("home"); }}>Back</button></section>}{view === "review" && <section><p className="eyebrow">PHOTO REVIEW</p><h2>Ready to analyze</h2><p>{file?.name ?? "No selected image"}</p><p className="hint">The image is only in memory. Cancelling or replacing clears the active request.</p><button disabled={!file || busy} onClick={submit}>{busy ? "Uploading…" : "Confirm and analyze"}</button>{busy && <button className="secondary" onClick={cancel}>Cancel upload</button>}<button className="secondary" disabled={busy} onClick={() => { clear(); setView("guidance"); }}>Replace photo</button></section>}{view === "analysis" && result && <section><p className="eyebrow">{result.is_mock ? "DEMO ANALYSIS" : "AI ANALYSIS"}</p><h2>Observation result</h2><div className="card"><strong>Observed damage category</strong><p>{categoryLabel(result.damage_category)}</p><strong>Confidence</strong><p>{Math.round(result.confidence * 100)}%</p><p>{result.summary}</p></div>{isBlocked(result) ? <div className="blocked"><strong>DIY repair guidance is not available for this result.</strong><p>{result.next_action || "Retake a clearer photo or seek professional help for uncertain or unsupported damage."}</p></div> : <div className="card"><strong>Clean-cut result received</strong><p>Further browser repair steps are coming next. No repair guidance is shown in this web build.</p></div>}<List title="Evidence" values={result.evidence}/><List title="Unknowns" values={result.unknowns}/><List title="Safety flags" values={result.safety_flags}/><div className="card"><strong>Next action</strong><p>{result.next_action}</p></div><button onClick={() => { clear(); setView("home"); }}>Start over</button><button className="secondary" onClick={() => { clear(); setView("guidance"); }}>Choose another photo</button></section>}</main>;
}
function List({ title, values }: { title: string; values: string[] }): React.JSX.Element { return <div className="card"><strong>{title}</strong><ul>{values.length ? values.map(value => <li key={value}>{value}</li>) : <li>None provided</li>}</ul></div>; }
createRoot(document.getElementById("root")!).render(<App/>);
